config/routes.rb
Rails.application.routes.draw do
  
  # scope "(:locale)", :locale => /#{I18n.available_locales.join('|')}/ do
    localized do
      devise_for :users, :path => "auth", path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { cas_sessions: 'my_cas' }

      get '/home', to: 'home#index', as: 'home'

      get 'help', to: 'pages#help', defaults: { format: :html }, constraints: { format: :html }
      get 'manual', to: 'pages#manual', defaults: { format: :html }
      get 'changelog', to: 'pages#changelog', defaults: { format: :html }, constraints: { format: :html }
      get 'news', to: 'home#news', defaults: { format: :json }, constraints: { format: :json }, as: :news

      concern :attachable do
        patch :attachment_create, on: :member
        patch :attachment_update
        delete 'attachments/:file_id/delete', on: :member, action: :attachment_destroy, as: :attachment_destroy #, on: :member #, defaults: { format: :js }, constraints: { format: :js }
        get 'attachments/:file_id/download', on: :member, action: :attachment_download, as: :attachment_download
        get :attachments, on: :member
      end

      scope path: '/admin' do
        get :index, to: 'home#admin', as: :admin, defaults: { format: :html }, constraints: { format: :html }
        get :logs, to: 'home#logs'
        get :historicizes, to: 'home#historicizes', defaults: { format: :js }, constraints: { format: :js }
        resources :matrix_types, except: [ :show ] do 
          get 'category', on: :collection, to: 'matrix_types#new', new_category: true, as: 'new_category'
        end
        resources :units, except: [ :show ]
        resources :analisy_types, except: [ :show ]
        resources :nuclides, except: [ :show ]
        resources :instructions, except: [ :show ] do
          get :download, on: :member
        end
        resources :users do
          put 'lock', on: :member, to: 'users#lock'
          put 'unlock', on: :member, to: 'users#unlock'
        end
      end

      resources :jobs, concerns: [ :attachable ] do
        get 'show(/:section)', on: :member, to: 'jobs#show', as: :section, section: /details|contacts|design|roles|attachments/
        get 'print', on: :member, to: 'jobs#print'
        get 'analisies', on: :member, to: 'jobs#analisies'
        get 'printed', on: :member, to: 'jobs#printed', defaults: { format: :pdf }, constraints: { format: :pdf }
        get 'search', on: :collection, defaults: { format: :html }, constraints: { format: :html }
        get 'logs', on: :member, to: 'jobs#logs'
        get 'reopen', on: :member, to: 'jobs#reopen', defaults: { format: :html }, constraints: { format: :html }
        post 'reopened', on: :member, to: 'jobs#reopen', defaults: { format: :js }, constraints: { format: :js }
        get 'deleted', on: :collection, to: 'jobs#deleted', defaults: { format: :html }, constraints: { format: :html }
        get 'edit(/:section)', on: :member, to: 'jobs#edit', as: :section_edit, section: /details|contacts|design|roles|attachments/, defaults: { format: :html }
        resources :import, only: :index do
          get :template, on: :collection, to: 'import#template', defaults: { format: :xlsx }, constraints: { format: :xlsx }
          post :verify, on: :collection, to: 'import#verify' #, defaults: { format: :js }, constraints: { format: :js }
          put :create, on: :collection, to: 'import#create', defaults: { format: :js }, constraints: { format: :js }
        end
        resources :timetables do
          get '(/:section)', on: :collection, to: 'timetables#index', section: /table/, as: :section #, defaults: { format: :html }
          get 'template', on: :collection, to: 'timetables#template', template: /standard|radon/, defaults: { format: :html }, constraints: { format: :html }
          get 'print', on: :collection, to: 'timetables#print', defaults: { format: :xlsx }, constraints: { format: :xlsx }
          put 'changeorder', on: :member, to: 'timetables#changeorder', defaults: { format: :js }, constraints: { format: :js }
        end
        resources :samples do
          resources :analisies do
            resources :results, only: :none do
              match 'results', via: [:get, :patch], on: :collection, to: 'analisies#results', defaults: { format: :html }, constraints: { format: :html }
              get 'edit', on: :member, to: 'analisies#result_edit', defaults: { format: :html }, constraints: { format: :html }, as: :edit
            end
          end
        end
        resources :analisies, only: [:index]
        resources :reports, only: [:index, :create, :delete, :destroy] do
          get '(/:section)(/:report_type)', on: :collection, to: 'reports#index', section: /issued|notissued|cancelled/, report_type: /single|multiple/, as: :filtered
          get :download, on: :member, to: 'reports#download', as: :download, defaults: { format: :pdf }, constraints: { format: :pdf }
          get :delete, on: :member, to: 'reports#delete', as: :delete

        end
      end
      get 'notauthorized', :to => redirect('/401.html')
    end

    root 'home#index'
  #end

  # get '/:locale', to: 'home#index'
end

app/models/analisy.rb
class Analisy < ApplicationRecord
  belongs_to :sample, :class_name => "Sample", :foreign_key => "sample_id"
  belongs_to :type, :class_name => "AnalisyType", :foreign_key => "analisy_type_id"
  has_one    :job, :through => :sample, source: :job
  has_one    :report, -> { issued }, :class_name => 'Report', dependent: :destroy
  has_many   :results, :class_name => "AnalisyResult", :foreign_key => "analisy_id"
  has_many   :nuclides, :through => :results, source: :nuclide
 
  has_many :reports, through: :results, source: :reports
  
  has_many :roles, -> { order role: :asc }, :class_name => "AnalisyUser", :foreign_key => "analisy_id"
  has_many :analisy_technics, -> { where role: 'technic' }, :class_name => "AnalisyUser", :foreign_key => "analisy_id", before_add: [Proc.new {|p,d| d.role = 2} ]
  has_many :analisy_headtests, -> { where role: 'headtest' }, :class_name => "AnalisyUser", :foreign_key => "analisy_id", before_add: [Proc.new {|p,d| d.role = 1} ]
  has_many :analisy_chiefs, -> { where role: 'chief' }, :class_name => "AnalisyUser", :foreign_key => "analisy_id", before_add: [Proc.new {|p,d| d.role = 0} ]
  has_many :analisy_chief_users, :through => :analisy_chiefs, source: :user
  has_many :analisy_headtest_users, :through => :analisy_headtests, source: :user
  has_many :analisy_technic_users, :through => :analisy_technics, source: :user

  accepts_nested_attributes_for :sample, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :analisy_chief_users, reject_if: lambda { |user| user[:_destroy].blank? && user[:id].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :analisy_headtest_users, reject_if: lambda { |user| user[:_destroy].blank? && user[:id].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :analisy_technic_users, reject_if: lambda { |user| user[:_destroy].blank? && user[:id].blank? }, :allow_destroy => true
  
  accepts_nested_attributes_for :results, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reports, reject_if: :all_blank, allow_destroy: true

  has_many :logs, as: :loggable
  accepts_nested_attributes_for :logs, :reject_if => :all_blank, :allow_destroy => true

  attr_accessor :author, :skip_validate, :sample_attributes

  before_validation :prerequisite

  validates :analisy_type_id, presence: true, uniqueness: { :scope => :sample_id }
  validates :reference_at, presence: true, date: true
  
  validates :analisy_chief_user_ids, presence: true, :unless => Proc.new { |analisy| analisy.skip_validate == 'true' }
  validates :analisy_headtest_user_ids, presence: true, :unless => Proc.new { |analisy| analisy.skip_validate == 'true' }
  validates :analisy_technic_user_ids, presence: true, :unless => Proc.new { |analisy| analisy.skip_validate == 'true' }

  before_save :create_log

  default_scope { order(sample_id: :asc, code: :asc) }


  scope :created_in, ->(year) { where( "extract(YEAR from created_at ) = ?", year ) }

  def reference_on
    I18n.l reference_at.to_date if reference_at.present?
  end

  def created_on
    I18n.l created_at.to_date if created_at.present?
  end

  def fullcode
    return "#{ created_at.strftime('%Y') }-#{ code }"
  end

  private

  def prerequisite
    self.author = 'System' if author.blank? || author.nil?
    self.reference_at = Time.now if reference_at.blank?
    analisy_headtests_exists?
    analisy_technics_exists?
  end

  def analisy_headtests_exists?
    if analisy_headtest_user_ids.present?
      analisy_headtest_user_ids.each do | user_id |
        self.analisy_headtest_user_ids.delete(user_id) unless User.headtests.pluck(:id).include?( user_id )
      end
    end
    return analisy_headtest_user_ids.present?
  end
  def analisy_technics_exists?
    if analisy_technic_user_ids.present?
      analisy_technic_user_ids.each do | user_id |
        self.analisy_technic_user_ids.delete(user_id) unless User.technics.pluck(:id).include?( user_id )
      end
    end
    return analisy_technic_user_ids.present?
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  include AttachableController
  include ImportableController
  before_action :set_user
  load_and_authorize_resource
  before_action :set_job
  before_action :set_samples
  before_action :set_sample, only: [:show, :edit, :update, :destroy]
  respond_to :html, only: [:index, :new, :edit]
  respond_to :js, only: [:new, :edit, :create, :update, :destroy]
  respond_to :json, only: [:index, :update]

  before_action do
    add_breadcrumb "<i class='fa fa-table'> #{I18n.t("breadcrumbs.jobs.all")}</i>".html_safe, :jobs_path, :title => I18n.t("breadcrumbs.jobs.return")
    add_breadcrumb "<i class='fa fa-edit text-trim'> #{@job.title}</i>".html_safe, edit_job_path(id: @job.id), :title => I18n.t("breadcrumbs.jobs.edit")
    add_breadcrumb "<i class='fa fa-table'> #{I18n.t("breadcrumbs.samples.all")}</i>".html_safe, :job_samples_path, :title => I18n.t("breadcrumbs.samples.return")
  end
  # GET /samples
  # GET /samples.json
  def index
    @section = 'samples'
    @modal = params[:modal]
    respond_to do |format|
      format.html do
        @samples = @samples.page( params[:page] )
        if params[:modal] == "1"
          @samples = @samples.per(5)
          @modal = params[:modal]
          @title = @job.title
          @icon = ("<i class='fa fa-eye'></i> <span id='title-label'>#{@job.code}</span>").html_safe
          @menu = [
            {fa: 'list', text: t('details', scope: 'jobs', default: 'Details'), to: job_path(id: @job.id, section: 'details', modal: @modal), remote: true},
            {fa: 'fax', text: t('contacts', scope: 'jobs', default: 'Contacts'), to: job_path(id: @job.id, section: 'contacts', modal: @modal), remote: true},
            {fa: 'calendar', text: t('title', scope: 'timetables', default: 'Timetables'), to: job_timetables_path(job_id: @job.id, modal: @modal), remote: true},
            {fa: 'flask', text: t('title', scope: 'samples', default: 'Timetables'), to: job_samples_path(job_id: @job.id, modal: @modal), remote: true, class: 'selected'},
          ]
          @edit = ( {fa: 'edit', to: edit_job_path(id: @job.id), remote: false, confirm: 'Sei sicuro di voler modificare questi dati?' } if can?(:update, @job) )
          render layout: 'modal'
        end
      end
      format.js
      format.json do
        @samples = @samples.left_outer_joins(:type_matrix).left_outer_joins(:analisies)
        dt_filter( @samples )
      end
    end
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
    @modal = params[:modal]
    respond_to do |format|
      format.html do
        if params[:modal] == "1"
          @modal = params[:modal]
          @icon = ("<i class='fa fa-eye'></i> ")
          @title = "#{t('title', scope: 'samples.show', default: 'Show')}"
          render layout: 'modal'
        end
        add_breadcrumb "<i class='fa fa-table'> #{I18n.t("breadcrumbs.samples.show")}</i>".html_safe
      end
      format.js
    end
  end

  # GET /samples/new
  def new
    @sample = @job.samples.new(sample_params)
    @users = User.all.select(:id, :label).pluck(:label, :id)
    @analisy_types = AnalisyType.all.pluck(:title, :id)
    @categories = MatrixType.categories
    # @matrices = :nil #MatrixType.all
    if params[:modal] == "1"
      @modal = params[:modal]
      @rid = params[:rid]
      @icon = ("<i class='fa fa-cube'></i> ")
      @title = t('title', scope: 'samples.new', default: 'New sample')
      render layout: 'modal'
    end
    add_breadcrumb "<i class='fa fa-table'> #{I18n.t("breadcrumbs.samples.new")}</i>".html_safe
  end

  # GET /samples/1/edit
  def edit
    @users = User.all.select(:id, :label).pluck(:label, :id)
    @analisy_types = AnalisyType.all.pluck(:title, :id)
    @analisies = @sample.analisies
    @categories = MatrixType.categories
    @matrices = @sample.type_matrix.blank? ? MatrixType.matrices : MatrixType.matrices.where(pid: @sample.type_matrix.pid)
    @sample.category_id = @sample.type_matrix.pid unless @sample.type_matrix.blank?
    if params[:modal] == "1"
      @modal = params[:modal]
      @icon = ("<i class='fa fa-cube'></i> ")
      @title = "#{t('title', scope: 'samples.edit', default: 'Edit sample')} #{@sample.code}"
      render layout: 'modal'
    end
    add_breadcrumb "<i class='fa fa-table'> #{I18n.t("breadcrumbs.samples.edit")}</i>".html_safe
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = @job.samples.new(sample_params)
    @sample.author = current_user.label unless @sample.author.blank?
    @sample.created_by = current_user.label
    @sample.updated_by = current_user.label
    @users = User.all.select(:id, :label).pluck(:label, :id)
    @analisy_types = AnalisyType.all.pluck(:title, :id)
    @analisies = @sample.analisies
    @categories = MatrixType.categories
    @matrices = MatrixType.all if @sample.type_matrix_id.present?
    @sample.category_id = @sample.type_matrix.pid unless @sample.type_matrix.blank?
    respond_to do |format|
      if @sample.save
        format.html { redirect_to job_samples_path(job_id: @job.id), notice: I18n.t('notice', scope: 'samples.create', default: 'Sample was successfully created.') }
        format.js
        format.json { render :show, status: :created, location: @sample }
      else
        puts @sample.errors.full_messages.join(', ')
        format.html { render :new }
        format.js
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samples/1
  # PATCH/PUT /samples/1.json
  def update
    @sample.author = current_user.label
    @sample.updated_by = current_user.label
    @modal = params[:modal]
    @users = User.all.select(:id, :label).pluck(:label, :id)
    @categories = MatrixType.categories
    @matrices = MatrixType.all
    @modal = params[:modal]
    respond_to do |format|
      if @sample.update_attributes(sample_params)
        format.html { redirect_to job_samples_path(job_id: @job.id), notice: I18n.t('notice', scope: 'samples.update', default: 'Sample was successfully updated.') }
        format.js
        format.json { render :show, status: :created, location: @sample }
      else
        format.html{ render :edit }
        format.js
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample.author = current_user.label
    @sample.destroy
    @samples = @job.samples
    respond_to do |format|
      format.html { redirect_to job_samples_path(job_id: @job.id), notice: I18n.t('notice', scope: 'samples.destroy', default: 'Sample was successfully destroyed.') }
      format.js
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = current_user
    end

    def set_job
      @job = Job.find(params[:job_id])
    end

    def set_samples
      @samples = @job.samples.distinct
    end

    def set_sample
      @sample = @samples.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_params
      params.fetch(:sample, {}).permit(:id, :job_id, :timetable_id, :device, :client_code, :author_id, :code, :accepted_at, :report, :cod_sample_client, :start_at, :stop_at, :reference_at, :latitude, :longitude, :category_id, :type_matrix_id, :conservation, :body, :author, :skip_presence, analisies_attributes: [ :id, :code, :sample_id, :analisy_type_id, :date_at, :reference_at, :method, :body, :author, :done, :_destroy, :skip_validate, analisy_chiefs_attributes: [ :id, :user_id ], analisy_headtests_attributes: [ :id, :user_id ], analisy_technic_user_ids: [], nuclide_ids: []  ]  )
    end
end

app/views/samples/_analisy_fields.html.haml
- if can?(:create, f => Analisy) || can?(:update, f.object)
	%tr.nested-fields{ class: "#{ 'new' if f.object.new_record? }  " }
		%td.small-1.text-center.field
			= f.object.code.blank? ? 'Nuovo' : f.object.code
			= f.hidden_field :skip_validate, value: true
			= f.hidden_field :id, value: f.object.id
			= f.hidden_field :author, value: current_user.label
		%td.small-5.field= f.select_field :analisy_type_id, AnalisyType.all.map{ |m| [ m.title, m.id ] }, { include_blank: false, label: 'false' }, { class: 'input-group-field select2' }
		%td.small-5.results.field= f.select_field :nuclide_ids, Nuclide.all.map{ |m| [ m.title, m.id ] }, { include_blank: false, label: 'false' }, { class: 'input-group-field select2', multiple: 'multiple' }
		%td.small-1.text-center= link_to_remove_association fa_icon('trash', class: 'button alert radius small expanded'), f
- else
	- unless f.object.job.blank?
		%tr
			%td.small-1.text-center= f.object.code
			%td.small-5= f.object.type.title
			%td.small-5.results
				%ul
					- f.object.results.each do | result |
						%li= result.full_result_with_nuclide
			%td.small-1.text-center.button-group
				= link_to fa_icon( 'search' ), job_sample_analisy_path(job_id: f.object.job.id, sample_id: f.object.sample_id, id: f.object.id), class: 'button transparent', data: { confirm: t('analisies', scope: 'jobs.redirect.confirmation', default: 'Are you sure?') } if can? :read, f.object
				= link_to fa_icon( 'print' ),  download_job_sample_analisy_path(job_id: f.object.job.id, sample_id: f.object.sample_id, id: f.object.id), class: 'button transparent', target: '_blank' if can? :print, f.object

app/views/samples/_form.html.haml
= form_with model: @sample, url: [@job, @sample], local: !(@modal == '1'), :builder => ExtraFormWith do |f|
  .container
    %div.text-bold.text-upcase.text-warning= t('title', scope: 'samples.show', default: "Sample details")
    .grid-y
      - if @sample.errors.any?
        .cell.grid-x.grid-padding-x
          .error_explanation
            %h2= #{pluralize(@sample.errors.count, "error")} bloccano il salvataggio di questo campione:
            %ul
            - @user.errors.full_messages.each do |msg|
              %li= msg
      .cell.grid-x.grid-padding-x
        - if @sample.persisted?
          .small-12.medium-6.cell= f.label_field :lab_code, options: { icon: 'barcode', placeholder: @sample.lab_code, help_text: "Codice composto dal codice univoco del campione, generato automaticamente dal sistema durante l'inserimento del campione, e il codice di importazione, se presente." }
        .small-12.medium-6.cell= f.text_field :client_code, autocomplete: "off", icon: 'barcode'
      .cell.grid-x.grid-padding-x
        .small-12.medium-4.cell= f.date_time_field :start_at, icon: 'calendar', autocomplete: 'false'
        .small-12.medium-4.cell= f.date_time_field :stop_at, icon: 'calendar', autocomplete: 'false'
        .small-12.medium-4.cell= f.label_field :accepted_at, options: { required: false, placeholder: @sample.accepted_on || l(Date.today), icon: 'calendar' }
      .cell.grid-x.grid-padding-x
        .large-6.cell= f.text_field :latitude, autocomplete: "off", icon: 'map-o', help_text: "espressa in gradi decimali", value: number_with_precision(@sample.latitude, strip_insignificant_zeros: true, precision: 14, separator: '.', delimiter: '' )
        .large-6.cell= f.text_field :longitude, autocomplete: "off", icon: 'map-o', help_text: "espressa in gradi decimali", value: number_with_precision(@sample.longitude, strip_insignificant_zeros: true, precision: 14, separator: '.', delimiter: '' )
      .cell.grid-x.grid-padding-x
        .small-12.medium-6.large-6.cell= f.select_field :category_id, [['Seleziona uno dei seguenti valori', '']] + @categories.map{ |m| [ m.title, m.id ] }, { icon: 'list', include_blank: false }, { class: 'input-group-field select2 category_id', selected: '' }
        .small-12.medium-6.large-6.cell= f.select_field :type_matrix_id, @matrices.present? ? @matrices.map{ |m| [ m.title, m.id ] } : [] , { icon: 'list', include_blank: false }, { class: 'input-group-field select2 matrices', disabled: ( @sample.type_matrix_id.blank? ? true : false ), data: { placeholder: 'Seleziona uno dei seguenti valori' } }
      .cell.grid-x.grid-padding-x
        .small-12.medium-6.large-6.cell= f.textarea :conservation, autocomplete: "off", icon: 'snowflake-o'
        .small-12.medium-6.large-6.cell= f.textarea :report, autocomplete: "off", icon: 'pencil'
      .cell= f.textarea :body, autocomplete: "off", icon: 'pencil'
      .cell.grid-x.grid-padding-x
        .small-12.medium-6.large-6.cell
          .grid-x.grid-padding-x
            .small-12.medium-6.large-8.cell= f.label_field :created_by, options: { required: 'false', placeholder: @sample.new_record? ? current_user.label : @sample.created_by, icon: 'user' }
            .small-12.medium-6.large-4.cell= f.label_field :created_at, options: { required: 'false', placeholder: @sample.new_record? ? l(Date.today) : l(@sample.created_at), icon: 'calendar' }
        .small-12.medium-6.large-6.cell
          .grid-x.grid-padding-x
            .small-12.medium-6.large-8.cell= f.label_field :updated_by, options: { required: 'false', placeholder: current_user.label, icon: 'user' }
            .small-12.medium-6.large-4.cell= f.label_field :updated_at, options: { required: 'false', placeholder: @sample.new_record? ? l(Date.today) : l(@sample.updated_at), icon: 'calendar' }

      .cell
        .container
          .small-12.large-6.cell
            %div.text-bold.text-upcase.text-warning= t('measure_type', scope: 'samples.fields', default: "Measure type")
          - if can?(:create, Analisy, sample_id: @sample.id) || can?(:update, Analisy, sample_id: @sample.id)
            .links.small-12.large-6.text-right.cell= link_to_add_association fa_icon('plus', text: 'Aggiungi analisi'), f, :analisies, class: 'button small radius add-button', 'data-association-insertion-node' => "#analisies", 'data-association-insertion-method' => "append"
          .small-12.cell
            %table#analisies
              %thead
                %th.text-center{ style: "width:150px;" }= fa_icon 'hashtag'
                %th= t('title', scope: 'analisytypes', default: "Analisy types" )
                %th{ style: "width:600px;" }= t('title', scope: 'nuclides', default: "Nuclides")
                %th{ style: "width:100px;" }
              %tbody
                = f.fields_for :analisies do |analisy|
                  = render 'analisy_fields', f: analisy
      .cell= f.submit_button

app/views/samples/_menu.html.haml
- if @sample.blank?
	%ul.menu.nav-menu.vertical.border-radius
		%li.title= fa_icon('cubes', text: t( 'titles', scope: 'samples.new', default: 'Add samples' ) )
		- if can?(:create, @job => Sample)
			%li= link_to fa_icon('plus', text: t('title', scope: 'samples.new', default: 'Create new sample') ), new_job_sample_path( job_id: @job.id ), class: 'reveal-modal', data: { url: new_job_sample_path(job_id: @job, modal: 1) }
- if @sample.present? && can?(:destroy, @sample)
	= link_to fa_icon( 'trash', text: t('title', scope: 'samples.destroy', default: 'Delete sample' ) ), job_sample_path(@sample), method: :delete, data: {confirm: t('delete', scope: 'confirmations', default: 'The deleted data can not be recovered. If you confirm, all data, connected to it, will be deleted. Are you sure?' ) }, class: 'button alert expanded'

app/views/samples/_new.html.haml
= render 'summary', job: @job, sample: '', analisy: '' unless @rid == '1'
#sample
	#form= render 'form'

app/views/samples/_show.html.haml
%h4.text-center= "#{t('title', scope: 'samples.show', default: "Sample details")} #{ @sample.lab_code }"
= render 'summary', job: @job, sample: @sample, analisy: ''
= render 'analisies/analisies'

app/views/samples/create.js.erb
<% if @sample.errors.blank? %>
  if( $('html').hasClass('is-reveal-open') ) {
    $('#myModal').foundation('close');
  } else {
    $('#sample #form').html("<%= escape_javascript( render 'form' ) %>");
    alert( 'Campione creato!' );
  }
<% else %>
  $('#sample #form').html("<%= escape_javascript( render 'form' ) %>");
<% end %>

app/views/samples/destroy.js.erb
<% if @samples.present? %>
  if ( $('#content').find( '.dataTable' ).length > 0 ) {
    $('.dataTable').DataTable().ajax.reload( null, false );
  }
<% else %>
  $('#samples').replaceWith("<%= escape_javascript( render 'samples' ) %>");
  samples_table();
<% end %>

app/views/samples/edit.html.haml
= render 'edit', job: @job, sample: @sample, analisies: @analisies, section: @section
- unless @modal == '1'
  - content_for :left do
    = render 'left_bar'

app/views/samples/edit.js.erb
$('#modal-body').html("<%= escape_javascript( render 'edit', job: @job, sample: @sample, analisies: @analisies, section: @section ) %>");

app/views/samples/index.js.erb
$('#modal-body').html("<%= escape_javascript(render 'samples', samples: @samples)%>");
samples_table();

app/views/samples/new.html.haml
= render 'new'
- unless @modal == '1'
  - content_for :left do
    = render 'left_bar'

app/views/samples/show.html.haml
= render 'show'
- unless @modal == '1'
  - content_for :left do
    = render 'left_bar'

app/views/samples/show.js.erb
$('#modal-body').html("<%= escape_javascript( render 'show' ) %>");
analisies_table();

app/views/samples/update.js.erb
<% if @sample.errors.blank? %>
  if ( $('html').hasClass('is-reveal-open') == true ) {
    $('#myModal').foundation('close');
  }else{
    $('#sample').html("<%= escape_javascript( render 'edit' ) %>");
    alert('Modifica avvenuta con successo!');
  }
<% else %>
  if ( $('html').hasClass('is-reveal-open') == true ) {
    $('#modal-body').html("<%= escape_javascript( render 'form' ) %>");
  }else{
    $('#sample').html("<%= escape_javascript( render 'edit' ) %>");
    alert("La modifica non è avvenuta a causa di <%= @sample.errors.count %> errori!");
  }
<% end %>