config/routes.rb
Rails.application.routes.draw do
  
  # scope "(:locale)", :locale => /#{I18n.available_locales.join('|')}/ do
    localized do
      devise_for :users, :path => "auth", path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { cas_sessions: 'my_cas' }

      get '/home', to: 'home#index', as: 'home'

      get 'help', to: 'pages#help', defaults: { format: :html }, constraints: { format: :html }
      get 'manual', to: 'pages#manual', defaults: { format: :html }
      get 'changelog', to: 'pages#changelog', defaults: { format: :html }, constraints: { format: :html }
      get 'news', to: 'home#news', defaults: { format: :json }, constraints: { format: :json }, as: :news

      concern :attachable do
        patch :attachment_create, on: :member
        patch :attachment_update
        delete 'attachments/:file_id/delete', on: :member, action: :attachment_destroy, as: :attachment_destroy #, on: :member #, defaults: { format: :js }, constraints: { format: :js }
        get 'attachments/:file_id/download', on: :member, action: :attachment_download, as: :attachment_download
        get :attachments, on: :member
      end

      scope path: '/admin' do
        get :index, to: 'home#admin', as: :admin, defaults: { format: :html }, constraints: { format: :html }
        get :logs, to: 'home#logs'
        get :historicizes, to: 'home#historicizes', defaults: { format: :js }, constraints: { format: :js }
        resources :matrix_types, except: [ :show ] do 
          get 'category', on: :collection, to: 'matrix_types#new', new_category: true, as: 'new_category'
        end
        resources :units, except: [ :show ]
        resources :analisy_types, except: [ :show ]
        resources :nuclides, except: [ :show ]
        resources :instructions, except: [ :show ] do
          get :download, on: :member
        end
        resources :users do
          put 'lock', on: :member, to: 'users#lock'
          put 'unlock', on: :member, to: 'users#unlock'
        end
      end

      resources :jobs, concerns: [ :attachable ] do
        get 'show(/:section)', on: :member, to: 'jobs#show', as: :section, section: /details|contacts|design|roles|attachments/
        get 'print', on: :member, to: 'jobs#print'
        get 'analisies', on: :member, to: 'jobs#analisies'
        get 'printed', on: :member, to: 'jobs#printed', defaults: { format: :pdf }, constraints: { format: :pdf }
        get 'search', on: :collection, defaults: { format: :html }, constraints: { format: :html }
        get 'logs', on: :member, to: 'jobs#logs'
        get 'reopen', on: :member, to: 'jobs#reopen', defaults: { format: :html }, constraints: { format: :html }
        post 'reopened', on: :member, to: 'jobs#reopen', defaults: { format: :js }, constraints: { format: :js }
        get 'deleted', on: :collection, to: 'jobs#deleted', defaults: { format: :html }, constraints: { format: :html }
        get 'edit(/:section)', on: :member, to: 'jobs#edit', as: :section_edit, section: /details|contacts|design|roles|attachments/, defaults: { format: :html }
        resources :import, only: :index do
          get :template, on: :collection, to: 'import#template', defaults: { format: :xlsx }, constraints: { format: :xlsx }
          post :verify, on: :collection, to: 'import#verify' #, defaults: { format: :js }, constraints: { format: :js }
          put :create, on: :collection, to: 'import#create', defaults: { format: :js }, constraints: { format: :js }
        end
        resources :timetables do
          get '(/:section)', on: :collection, to: 'timetables#index', section: /table/, as: :section #, defaults: { format: :html }
          get 'template', on: :collection, to: 'timetables#template', template: /standard|radon/, defaults: { format: :html }, constraints: { format: :html }
          get 'print', on: :collection, to: 'timetables#print', defaults: { format: :xlsx }, constraints: { format: :xlsx }
          put 'changeorder', on: :member, to: 'timetables#changeorder', defaults: { format: :js }, constraints: { format: :js }
        end
        resources :samples do
          resources :analisies do
            resources :results, only: :none do
              match 'results', via: [:get, :patch], on: :collection, to: 'analisies#results', defaults: { format: :html }, constraints: { format: :html }
              get 'edit', on: :member, to: 'analisies#result_edit', defaults: { format: :html }, constraints: { format: :html }, as: :edit
            end
          end
        end
        resources :analisies, only: [:index]
        resources :reports, only: [:index, :create, :delete, :destroy] do
          get '(/:section)(/:report_type)', on: :collection, to: 'reports#index', section: /issued|notissued|cancelled/, report_type: /single|multiple/, as: :filtered
          get :download, on: :member, to: 'reports#download', as: :download, defaults: { format: :pdf }, constraints: { format: :pdf }
          get :delete, on: :member, to: 'reports#delete', as: :delete

        end
      end
      get 'notauthorized', :to => redirect('/401.html')
    end

    root 'home#index'
  #end

  # get '/:locale', to: 'home#index'
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  include AttachableController
  load_resource
  before_action :set_user
  before_action :search_params, except: [:new, :create, :update, :destroy, :print]
  before_action :set_jobs, except: [:index, :new, :create, :update, :destroy]
  before_action :set_job, only: [:show, :edit, :update, :destroy, :print, :logs, :reports, :create_multiple_reports, :destroy_multiple_reports, :reopen, :download]
  before_action :set_role, only: [:show, :edit, :update, :destroy, :print]
  respond_to :html, only: [:index, :show, :new, :edit, :print, :logs, :reopen, :deleted, :reports]
  respond_to :js, only: [:create, :update, :destroy, :reopen]
  respond_to :json, only: [:index, :show, :logs, :reports]
  respond_to :pdf, only: [:printed]

  before_action do
    add_breadcrumb "<i class='fa fa-briefcase'> #{I18n.t("breadcrumbs.jobs.all")}</i>".html_safe, :jobs_path, :title => I18n.t("breadcrumbs.jobs.return")
  end
  # GET /jobs
  # GET /jobs.json
  def index
    respond_to do |format|
      format.html
      format.json do
        dt_filter( @jobs )
      end
    end
  end

  def search
    if params[:modal] == "1"
      @modal = params[:modal]
      @icon = ("<i class='fa fa-search'></i> ")
      @title = "#{t('filter', scope: '', default: 'Filter')}"
      @other = "<span id='jobs_count'></span>"
      render layout: 'modal'
    end
  end

  def searched
  end

  def download
    attachment_download
  end

  def analisies
    @analisies = @job.analisies
    respond_to do |format|
      format.html do
        add_breadcrumb "<i class='fa fa-edit'> #{@job.title}</i>".html_safe, edit_job_path(id: @job.id), :title => I18n.t("breadcrumbs.samples.edit")
        add_breadcrumb "<i class='fa fa-table'> #{I18n.t("breadcrumbs.analisies.all")}</i>".html_safe
      end
      format.js
      format.json do
        @analisies = @analisies.joins(:sample).joins(:type)
        dt_filter( @analisies )
      end
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @section = params[:section] || 'details'
    @users = User.select(:id, :label)
    @chiefs = @users.chiefs
    @managers = @job.job_managers
    @technicians = @job.job_technicians
    if params[:modal] == "1"
      @modal = params[:modal]
      @title = @job.title
      @icon = ("<i class='fa fa-hashtag'></i> <span id='title-label'>#{@job.code}</span>").html_safe
      @menu = [
        {fa: 'file', text: t('details', scope: 'jobs', default: 'Details'), to: job_path(@job, modal: @modal), remote: true},
        {fa: 'table', text: t('title', scope: 'timetables', default: 'Timetables'), to: job_timetables_path(job_id: @job.id, modal: @modal), remote: true},
        {fa: 'table', text: t('title', scope: 'samples', default: 'Samples'), to: job_samples_path(job_id: @job.id, modal: @modal), remote: true},
        {fa: 'table', text: t('title', scope: 'analisies', default: 'Analisies'), to: job_analisies_path(job_id: @job.id, modal: @modal), remote: true},
        {fa: 'table', text: t('issued', scope: 'topbar.reports', default: 'Reports'), to: job_reports_path(job_id: @job.id, modal: @modal), remote: true},
        ( {fa: 'edit', title: t('title', scope: 'jobs.edit', default: 'Edit jobs'), to: edit_job_path(id: @job.id) } if can?( :update, @job ) ),
        ( {fa: 'external-link', title: t('title', scope: 'jobs.show', default: 'View details of jobs'), to: job_path(id: @job.id) } if cannot?( :update, @job ) && can?( :read, @job ) ),
      ]
      render layout: 'modal'
    end
    add_breadcrumb "<i class='fa fa-form'> #{I18n.t("breadcrumbs.jobs.show")}</i>".html_safe
  end

  # GET /jobs/new
  def new
    @managers = User.select(:id, :label).pluck(:label, :id)
    @chiefs = User.chiefs.select(:id, :label).pluck(:label, :id)
    @job = Job.new(author: @user)
    add_breadcrumb "<i class='fa fa-plus'> #{I18n.t("breadcrumbs.jobs.new")}</i>".html_safe
  end

  def create
    @job = Job.new(job_params)
    @job.author = current_user.label
    if @job.save
      # Invio e-mail Responsabili proc/att per avvisare della creazione del nuovo proc/att e del fatto di esssere stati indicati come Responsabili
      @job.job_managers.each do |manager|
        unless manager.email.blank?
          JobMailer.create(@job, manager, author: current_user, role: 'manager').deliver_now
        end
      end
      redirect_to edit_job_path(@job), notice: I18n.t('notice', scope: 'jobs.create', default: 'Job was successfully created.')
    else
      @managers = User.pluck(:label, :id)
      @chiefs = User.chiefs.pluck(:label, :id)
      render :new
    end
  end

  # GET /jobs/1/edit
  def edit
    @section = params[:section] || 'details'
    @users = User.select(:id, :label)
    @chiefs = @users.chiefs
    @managers = @users
    @technicians = @users
    @analisy_types = AnalisyType.all.pluck(:title, :id)
    @job.contacts.build if @job.contacts.blank?
    add_breadcrumb "<i class='fa fa-edit text-trim'> #{ @job.title }</i>".html_safe, edit_job_path(id: @job.id), :title => I18n.t("breadcrumbs.jobs.edit")
    add_breadcrumb I18n.t("breadcrumbs.jobs.sections.#{ @section }")
  end

  def update
    @job.author = current_user.label
    @section = params[:section] || 'details'
    @users = User.select(:id, :label)
    chief_before = @job.chief_id
    managers_before = @job.job_manager_ids
    technicians_before = @job.job_technician_ids
    closed_was = @job.closed?
    respond_to do |format|
      begin
        @job.assign_attributes(job_params)
      rescue ActiveRecord::RecordInvalid => invalid
        @errors = invalid.record.errors.full_messages.to_sentence
      rescue PG::UniqueViolation => invalid
        @errors = invalid.record.errors.full_messages.to_sentence
      end

      if @job.save
        if @job.chief.email.present? && chief_before != @job.chief_id
          JobMailer.create(@job, @job.chief, author: current_user, role: 'chief').deliver_later
        end
        @job.job_managers.each do |manager|
          if manager.email.present? && !managers_before.include?(manager.id)
            JobMailer.create(@job, manager, author: current_user, role: 'manager').deliver_later
          end
        end
        @job.job_technicians.each do |tech|
          if tech.email.present? && !technicians_before.include?(tech.id)
            JobMailer.create(@job, tech, author: current_user, role: 'technic').deliver_later
          end
        end
        if @job.closed? && closed_was == false
          redirect_to job_path( id: @job.id ), notice: I18n.t('notice', scope: 'jobs.closed', default: 'Job was successfully closed.')
        end
        format.html { redirect_to section_edit_job_path( id: @job.id, section: @section ), notice: I18n.t('notice', scope: 'jobs.update', default: 'Job was successfully updated.') }
        format.js do
          @chiefs = @users.chiefs
          @managers = @users.where.not(id: @job.chief_id)
          @technicians = @users.where.not(id: @job.chief_id)
          @job.contacts.build if @job.contacts.blank?
        end
        format.json { render :show, status: :ok, location: job_path(id: @job.id) }
      else
        format.html { redirect_to section_edit_job_path( id: @job.id, section: @section ), error: "#{@job.errors.messages.map{ |k,v| v }.join(', ')}" }
        format.js do
          @chiefs = @users.chiefs
          @managers = @users.where.not(id: @job.chief_id)
          @technicians = @users.where.not(id: @job.chief_id)
          @job.contacts.build if @job.contacts.blank?
        end
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.author = current_user.label
    respond_to do |format|
      if @job.destroy
        format.js
        format.html do
          redirect_to root_path, notice: I18n.t('notice', scope: 'jobs.destroy', default: 'Job was successfully deleted.')
        end
      else
        format.html do
          redirect_to root_path, error: I18n.t('error', scope: 'jobs.destroy', default: 'Job was not deleted.')
        end
      end
    end
  end

  def print
    if params[:modal] == "1"
      @modal = params[:modal]
      @title = @job.title
      @icon = ("<i class='fa fa-eye'></i> #{ t('print', scope: '', default: 'Print') }").html_safe
      render layout: 'modal'
    end
    add_breadcrumb "<i class='fa fa-print'> #{I18n.t("breadcrumbs.jobs.print")}</i>".html_safe
  end

  def printed
    @sections = print_params
    respond_to do |format|
      format.html
      format.pdf do
        require 'combine_pdf'
        template = @job.template.blank? ? Settings.config.template : @job.template
        pdf_data = template.constantize.send(:new, @job, @sections.except('single', 'multiple') )
        pdf_data = pdf_data.render
        combined_file = CombinePDF.new
        combined_file << CombinePDF.parse(pdf_data)
        if @sections[:single] == 'true'
          @job.reports.singles.each do | report |
            combined_file << CombinePDF.load(report.file.path)
          end
        end
        if @sections[:multiple] == 'true'
          @job.reports.multiples.each do | report |
            combined_file << CombinePDF.load(report.file.path)
          end
        end
        send_data combined_file.to_pdf, filename: "report_#{@job.code}.pdf", type: 'application/pdf'
      end
    end
  end

  def logs
    @nobar = true
    @logs = Log.joins(:job).where('job_id = ?', @job.id)
    respond_to do |format|
      format.html do
        add_breadcrumb "<i class='fa fa-edit'> #{@job.title}</i>".html_safe, edit_job_path(id: @job.id), :title => I18n.t("breadcrumbs.samples.edit")
        add_breadcrumb "<i class='fa fa-history'> #{I18n.t("breadcrumbs.jobs.logs")}</i>".html_safe
      end
      format.json do
        dt_filter( @logs )
      end
    end
  end

  def reopen
    @url = params[:url] #job_params[:url]
    respond_to do |format|
      format.html do
        @modal = params[:modal]

app/views/jobs/_attachments.html.haml
#contacts.section
  %fieldset
    %legend= t('title', scope: 'attachments', default: 'Attachments')
    %table
      %thead
        %tr
          %td.text-left= t('title', scope: 'attachments.fields', default: 'Title')
          %td.text-left= t('body', scope: 'attachments.fields', default: 'Note')
          %td.text-center= t('category', scope: 'attachments.fields', default: 'Category')
          %td.text-left
      %tbody
        - if @job.attachments.present?
          - @job.attachments.each do | attachment |
            %tr{ id: attachment.row }
              %td.text-left= attachment.title
              %td.text-justify= attachment.body
              %td.text-center= t( attachment.category, scope: 'attachement.categories', default: "#{attachment.category}".capitalize )
              %td.text-left= link_to fa_icon('download', title: attachment.file_file_name), attachment_download_job_path( id: @job.id, file_id: attachment.id ) , target: '_blank'
        - else
          %tr
            %td.text-center{ colspan: 4 } Nessun allegato inserito

app/views/jobs/_contact_fields.html.haml
%fieldset.nested-fields
  %legend= f.object.new_record? ? 'Nuovo contatto' : ( f.object.priority? ? 'Contatto principale' : 'Contratto alternativo' )
  .grid-x.grid-padding-x.grid-margin-y.text-middle
    .small-12.large-10.cell= f.text_field :label, icon: 'user', label: t( 'label', scope: 'jobcontacts.fields', default: 'Label' )
    .small-12.large-2.cell= f.boolean_field :priority, icon: false, label: t( 'priority', scope: 'jobcontacts.fields', default: 'Label' ), checked: f.object.job.contacts.blank? && f.object.new_record? ? true : f.object.priority
  .grid-x.grid-padding-x.grid-margin-y
    .field.small-12.large-3.cell= f.text_field :tel1, icon: 'phone', label: t( 'tel1', scope: 'jobcontacts.fields', default: 'Tel1' )
    .field.field.small-12.large-3.cell= f.text_field :tel2, icon: 'phone', label: t( 'tel2', scope: 'jobcontacts.fields', default: 'tel2' )
    .field.small-12.large-3.cell= f.text_field :cell, icon: 'mobile', label: t( 'cell', scope: 'jobcontacts.fields', default: 'cell' )
    .field.small-12.large-3.cell= f.text_field :fax, icon: 'fax', label: t( 'fax', scope: 'jobcontacts.fields', default: 'fax' )
  .field.small-12.cell= f.text_field :email, icon: 'at', label: t( 'email', scope: 'jobcontacts.fields', default: 'email' )
  = link_to_remove_association "Rimuovi questo contatto", f, class: 'button small alert radius'

app/views/jobs/_contacts.html.haml
#contacts.section
  %fieldset
    %legend= t('contacts', scope: 'jobs', default: 'Contacts')
    .grid-x
      %label.small-4.cell= t('customer', scope: 'jobs.fields', default: 'Customer')
      %span.small-8.cell= @job.customer || 'n.d.'
    .grid-x
      %label.small-4.cell= t('address', scope: 'jobs.fields', default: 'Address')
      %span.small-8.cell= @job.address || 'n.d.'
    - @job.contacts.each do | contact |
      .grid-x
        %label.small-4.cell= t('contact', scope: 'jobs.fields', default: 'Contact')
        %span.small-8.cell= contact.contact || 'n.d.'
      .grid-x
        %label.small-4.cell= t('tel1', scope: 'jobs.fields', default: 'Tel1')
        %span.small-8.cell= contact.tel1 || 'n.d.'
      .grid-x
        %label.small-4.cell= t('tel2', scope: 'jobs.fields', default: 'Tel2')
        %span.small-8.cell= contact.tel2 || 'n.d.'
      .grid-x
        %label.small-4.cell= t('cell', scope: 'jobs.fields', default: 'Cell')
        %span.small-8.cell= contact.cell || 'n.d.'
      .grid-x
        %label.small-4.cell= t('fax', scope: 'jobs.fields', default: 'Fax')
        %span.small-8.cell= contact.fax || 'n.d.'
      .grid-x
        %label.small-4.cell= t('email', scope: 'jobs.fields', default: 'E-mail')
        %span.small-8.cell= contact.email || 'n.d.'

app/views/jobs/_design.html.haml
#details.section
  %fieldset
    %legend= t('registry', scope: 'jobs', default: 'Details')
    .grid-x
      %label.small-4.cell= t('institutions', scope: 'jobs.fields', default: 'Institutions')
      %span.small-8.cell= @job.institutions
    .grid-x
      %label.small-4.cell= t('other_resources', scope: 'jobs.fields', default: 'Other resources')
      %span.small-8.cell= @job.other_resources

app/views/jobs/_details.html.haml
#details.section
  %fieldset
    %legend= t('registry', scope: 'jobs', default: 'Details')
    .grid-x
      %label.small-4.cell= t('code', scope: 'jobs.fields', default: 'Job Code')
      %span.small-8.cell= @job.code
    .grid-x
      %label.small-4.cell= t('title', scope: 'jobs.fields', default: 'Title')
      %span.small-8.cell= @job.title
    .grid-x
      %label.small-4.cell= t('open_at', scope: 'jobs.fields', default: 'Open at')
      %span.small-8.cell= @job.open_on
    .grid-x
      %label.small-4.cell= t('planned_closure_at', scope: 'jobs.fields', default: 'Planned closure at')
      %span.small-8.cell= @job.planned_closure_on
    .grid-x
      %label.small-4.cell= t('close_at', scope: 'jobs.fields', default: 'Close at')
      %span.small-8.cell
        = @job.close_on
        = link_to fa_icon( 'unlock', text: t( 'title', scope: 'jobs.reopen', default: 'Reopen job' ) ), reopen_job_path(id: @job.id, url: edit_job_url( id: @job.id ) ), class: 'button alert small reveal-modal-mini', data: { url: reopen_job_path(id: @job.id, modal: '1', url: edit_job_url( id: @job.id ) ) } if can?( :reopen, @job ) && @modal.blank?
    .grid-x
      %label.small-4.cell= t('consolidated', scope: 'jobs.fields', default: 'Consolidated')
      %span.small-8.cell= t( "#{@job.consolidated}" )
    .grid-x
      %label.small-4.cell= t('pa_support', scope: 'jobs.fields', default: 'Support PA')
      %span.small-8.cell= t( "#{@job.pa_support}" )
    .grid-x
      %label.small-4.cell= t('requirements', scope: 'jobs.fields', default: 'Requirements')
      %span.small-8.cell= @job.requirements
    .grid-x
      %label.small-4.cell= t('body', scope: 'jobs.fields', default: 'Note')
      %span.small-8.cell= @job.body

app/views/jobs/_edit.html.haml
- if can? :update, @job
  #details= render 'jobs/edit_details', job: @job, section: section if @section == 'details'
  #contacts= render 'jobs/edit_contacts', job: @job, section: section if @section == 'contacts'
  - unless @job.consolidated?
    #design= render 'jobs/edit_design', job: @job, section: section if @section == 'design'
  #roles= render 'jobs/edit_roles', job: @job, section: section if @section == 'roles'
  #attachments= render 'jobs/edit_attachments', job: @job, section: section if @section == 'attachments'
- else
  .callout.alert.text-justify
    - reason = "Non sei abilitato a modificare questa area del proc/att "
    - if job.closed?
      - reason += "poichè è stata chiusa. Contattare il Responsabile del area."
    = reason

  = render 'jobs/show'

app/views/jobs/_edit_details.html.haml
= form_with model: job, url: job_path(id: job.id, section: 'details'), :builder => ExtraFormWith do |f|
  %h4.text-center= "#{ t('details', scope: 'jobs', default: 'Details') } #{ t('title', scope: 'jobs', default: 'Details').downcase }"
  .grid-x.grid-padding-x.grid-margin-y
    .medium-4.large-2.cell= f.label_field :code, options: { icon: 'hashtag', placeholder: job.code }
    .medium-8.large-8.cell= f.text_field :title, icon: 'pencil'
    .medium-12.large-2.cell
      .medium-6.large-12.cell= f.boolean_field :pa_support
      .medium-6.large-12.cell= f.boolean_field :consolidated
  .grid-x.grid-padding-x.grid-margin-y
    .medium-4.large-2.cell= f.date_field :open_at, icon: 'calendar', autocomplete: 'false'
    .medium-4.large-2.cell= f.date_field :planned_closure_at, icon: 'calendar', autocomplete: 'false'
    .medium-4.large-2.cell
      - if can? :close, job
        = f.date_field :close_at, icon: 'calendar', autocomplete: 'false', placeholder: job.close_on
      - else
        = f.label_field :close_at, options: { icon: 'calendar', placeholder: 'Non sei autorizzato' }
  .grid-x.grid-padding-x.grid-margin-y
    .medium-6.cell= f.textarea :requirements
    .medium-6.cell= f.textarea :body
  .grid-x.grid-padding-x.grid-margin-y= f.submit_button icon: 'save', value: t( 'submit', scope: 'jobs.update', default: 'Save' )

app/views/jobs/_new.html.haml
- if can?(:create, @job)
  = form_with model: @job, data: { remote: 'false' }, :builder => ExtraFormWith do |f|
    .container
      .grid-y
        .cell= f.text_field :title, icon: 'pencil', inline: true
        .cell= f.date_field :open_at, icon: 'calendar', autocomplete: 'false', inline: true
        .cell= f.date_field :planned_closure_at, icon: 'calendar', autocomplete: 'false', inline: true
        .cell= f.switch_field :pa_support, class: 'switch-input input-group-field', inline: true
        .cell= f.switch_field :consolidated, class: 'switch-input input-group-field', inline: true
        .cell= f.textarea :body, inline: true, icon: 'pencil', valign: 'top'
        .cell= f.select_field_if true, :chief_id, @chiefs,  options: { icon: 'user-secret', include_blank: false, inline: true }, input_options: { class: 'input-group-field' }
        .cell= f.select_field_if true, :job_manager_ids, @managers, options: { icon: 'users', placeholder: @job.job_managers.pluck(:label).join(', '), valign: 'top', inline: true }, input_options: { include_blank: false, class: 'select2 input-group-field ', multiple: 'multiple', required: 'required' }
      .grid-x.grid-padding-x.grid-margin-y= f.submit_button icon: 'save'

app/views/jobs/_reopen.html.haml
- if can?(:reopen, @job)
  = form_with model: @job, url: reopened_job_path(id: @job.id, url: @url), method: :post, remote: true, :builder => ExtraFormWith do |f|
    .container
      .grid-y
        .cell= f.textarea :reopen_reason
        .cell= f.submit_button icon: 'save', value: t( 'title', scope: 'jobs.reopen', default: 'Reopen job' )

app/views/jobs/analisies.html.haml
= render 'summary', job: @job, sample: '', analisy: ''
= render 'analisies/analisies'
- unless @modal == '1'
  - content_for :left do
    = render 'left_bar'

app/views/jobs/deleted.html.haml
- if current_user.admin?
  %table#jobs-deleted
    %thead
      %tr
        %th.text-center= t('code', scope: 'jobs.fields', default: 'Code')
        %th= t('title', scope: 'jobs.fields', default: 'Title')
        %th.text-center= t('open_at', scope: 'jobs.fields', default: 'Open at')
        %th.text-center= t('close_at', scope: 'jobs.fields', default: 'Close at')
        %th.text-center= t('job_type', scope: 'jobs.fields', default: 'Job type')
        %th.text-center= t('pa_support', scope: 'jobs.fields', default: 'Pa support')
        %th.small-1.text-center= t('timetable', scope: 'jobs.fields', default: 'Timetable')
        %th.small-1.text-center Campioni Inseriti/Previsti
        %th.small-2.text-right
    %tbody
      = render @jobs
    %tfooter

app/views/jobs/edit.html.haml
= render 'edit', job: @job, section: @section
= render 'left_bar' unless @modal == '1'

app/views/jobs/reopen.html.haml
= render 'reopen'

app/views/jobs/reopen.js.erb
<% unless @job.errors.blank? %>
  $('#modal-body').html("<%= escape_javascript( render 'reopen' ) %>");
<% end %>