config/routes.rb
Rails.application.routes.draw do
  
  # scope "(:locale)", :locale => /#{I18n.available_locales.join('|')}/ do
    localized do
      devise_for :users, :path => "auth", path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { cas_sessions: 'my_cas' }

      get '/home', to: 'home#index', as: 'home'

      get 'help', to: 'pages#help', defaults: { format: :html }, constraints: { format: :html }
      get 'manual', to: 'pages#manual', defaults: { format: :html }
      get 'changelog', to: 'pages#changelog', defaults: { format: :html }, constraints: { format: :html }
      get 'news', to: 'home#news', defaults: { format: :json }, constraints: { format: :json }, as: :news

      concern :attachable do
        patch :attachment_create, on: :member
        patch :attachment_update
        delete 'attachments/:file_id/delete', on: :member, action: :attachment_destroy, as: :attachment_destroy #, on: :member #, defaults: { format: :js }, constraints: { format: :js }
        get 'attachments/:file_id/download', on: :member, action: :attachment_download, as: :attachment_download
        get :attachments, on: :member
      end

      scope path: '/admin' do
        get :index, to: 'home#admin', as: :admin, defaults: { format: :html }, constraints: { format: :html }
        get :logs, to: 'home#logs'
        get :historicizes, to: 'home#historicizes', defaults: { format: :js }, constraints: { format: :js }
        resources :matrix_types, except: [ :show ] do 
          get 'category', on: :collection, to: 'matrix_types#new', new_category: true, as: 'new_category'
        end
        resources :units, except: [ :show ]
        resources :analisy_types, except: [ :show ]
        resources :nuclides, except: [ :show ]
        resources :instructions, except: [ :show ] do
          get :download, on: :member
        end
        resources :users do
          put 'lock', on: :member, to: 'users#lock'
          put 'unlock', on: :member, to: 'users#unlock'
        end
      end

      resources :jobs, concerns: [ :attachable ] do
        get 'show(/:section)', on: :member, to: 'jobs#show', as: :section, section: /details|contacts|design|roles|attachments/
        get 'print', on: :member, to: 'jobs#print'
        get 'analisies', on: :member, to: 'jobs#analisies'
        get 'printed', on: :member, to: 'jobs#printed', defaults: { format: :pdf }, constraints: { format: :pdf }
        get 'search', on: :collection, defaults: { format: :html }, constraints: { format: :html }
        get 'logs', on: :member, to: 'jobs#logs'
        get 'reopen', on: :member, to: 'jobs#reopen', defaults: { format: :html }, constraints: { format: :html }
        post 'reopened', on: :member, to: 'jobs#reopen', defaults: { format: :js }, constraints: { format: :js }
        get 'deleted', on: :collection, to: 'jobs#deleted', defaults: { format: :html }, constraints: { format: :html }
        get 'edit(/:section)', on: :member, to: 'jobs#edit', as: :section_edit, section: /details|contacts|design|roles|attachments/, defaults: { format: :html }
        resources :import, only: :index do
          get :template, on: :collection, to: 'import#template', defaults: { format: :xlsx }, constraints: { format: :xlsx }
          post :verify, on: :collection, to: 'import#verify' #, defaults: { format: :js }, constraints: { format: :js }
          put :create, on: :collection, to: 'import#create', defaults: { format: :js }, constraints: { format: :js }
        end
        resources :timetables do
          get '(/:section)', on: :collection, to: 'timetables#index', section: /table/, as: :section #, defaults: { format: :html }
          get 'template', on: :collection, to: 'timetables#template', template: /standard|radon/, defaults: { format: :html }, constraints: { format: :html }
          get 'print', on: :collection, to: 'timetables#print', defaults: { format: :xlsx }, constraints: { format: :xlsx }
          put 'changeorder', on: :member, to: 'timetables#changeorder', defaults: { format: :js }, constraints: { format: :js }
        end
        resources :samples do
          resources :analisies do
            resources :results, only: :none do
              match 'results', via: [:get, :patch], on: :collection, to: 'analisies#results', defaults: { format: :html }, constraints: { format: :html }
              get 'edit', on: :member, to: 'analisies#result_edit', defaults: { format: :html }, constraints: { format: :html }, as: :edit
            end
          end
        end
        resources :analisies, only: [:index]
        resources :reports, only: [:index, :create, :delete, :destroy] do
          get '(/:section)(/:report_type)', on: :collection, to: 'reports#index', section: /issued|notissued|cancelled/, report_type: /single|multiple/, as: :filtered
          get :download, on: :member, to: 'reports#download', as: :download, defaults: { format: :pdf }, constraints: { format: :pdf }
          get :delete, on: :member, to: 'reports#delete', as: :delete

        end
      end
      get 'notauthorized', :to => redirect('/401.html')
    end

    root 'home#index'
  #end

  # get '/:locale', to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  load_resource :job
  before_action :set_user
  before_action :search_params
  before_action :set_jobs, except: [:search, :logs, :historicizes]
  before_action :set_job, only: [:edit]
  before_action :set_role, only: [:edit]
  respond_to :html, only: [:index, :search, :edit, :logs]
  respond_to :json, only: [:index, :logs]
  respond_to :js, only: [:historicizes]

  before_action do
    unless params[:action] == 'admin' || params[:action] == 'logs'
      add_breadcrumb "<i class='fa fa-home'> #{I18n.t("breadcrumbs.jobs.home")}</i>".html_safe, :home_path, :except => %w( logs reports samples analisies historicizes )
    end
  end
  
  def index
    redirect_to jobs_path if @jobs.blank?
    respond_to do |format|
      format.html
      format.json do
        dt_filter( @jobs )
      end
    end
  end

  def admin
    add_breadcrumb "<i class='fa fa-gears'> #{I18n.t("breadcrumbs.admin.index")}</i>".html_safe, :admin_path, :title => I18n.t("breadcrumbs.admin.return")
  end

  def logs
    @nobar = true
    @logs = Log.left_outer_joins(:job)
    respond_to do |format|
      format.html do
        add_breadcrumb "<i class='fa fa-gears'> #{I18n.t("breadcrumbs.admin.index")}</i>".html_safe, :admin_path, :title => I18n.t("breadcrumbs.admin.return")
        add_breadcrumb "<i class='fa fa-history'> #{I18n.t("breadcrumbs.jobs.logs")}</i>".html_safe
      end
      format.json do
        dt_filter( @logs )
      end
    end
  end

  def historicizes
    Log.historicize( current_user )
  end

  def news
    from = params[:from]
    limit = params[:limit]
    news = []
    rows = Log.select(:job_id, :created_at).where("created_at >= ?", from).where("not job_id is null").distinct(:job_id).limit(limit)
    job_ids = rows.map{|r| r.job_id  }.uniq
    job_ids.each do |job_id| 
      news << Log.where(job_id: job_id).first
    end
    @news = news
  end

  private
    def set_user
      @user = current_user
    end

    def set_job
      @job = Job.find(params[:id])
    end

    def set_jobs
      @searched = search_params

      @status = @searched.present? && @searched[:status].present? ? @searched[:status] : 'opened'
      @consolidated = @searched.present? && @searched[:consolidated].present? ? @searched[:consolidated] : ''
      @role = @searched.present? && @searched[:role].present? ? @searched[:role] : ''

      @jobs = @user.jobs

      if @status.present?
        @jobs = @jobs.send(@status)
      end
      if @consolidated.present?
        @jobs = @jobs.where(consolidated: @consolidated)
      end
      if @role == 'manager'
        @jobs = @jobs.managers_list(user_id: @user.id)
      elsif @role == 'technic'
        @jobs = @jobs.technicians_list(user_id: @user.id)
      end

      @jobs = @jobs.distinct

    end

    def search_params
      params.require(:job).permit(:id, :status, :consolidated, :role, :format, :authenticity_token, :_, :locale, :modal, :section, :_method) if params[:job].present?
    end
end

app/views/home/admin.html.haml
#admin.grid-x.grid-margin-x.grid-margin-y.small-up-1.medium-up-4.large-up-6
	- if can? :update, User
		.cell
			.card.text-center
				= link_to users_path do
					.card-image= image_tag 'users.png', alt: ''
					.card-section= t('title', scope: 'topbar.users', default: 'Users Manage')
	- if can? :update, AnalisyType
		.cell
			.card.text-center
				= link_to analisy_types_path do
					.card-image= image_tag 'analisytypes.png', alt: ''
					.card-section= t('title', scope: 'topbar.analisytypes', default: "Manage analisy's types")
	- if can? :update, Instruction
		.cell
			.card.text-center
				= link_to instructions_path do
					.card-image= image_tag 'instructions.png', alt: ''
					.card-section= t('title', scope: 'topbar.instructions', default: "Manage operating instructions")
	- if can? :update, Nuclide
		.cell
			.card.text-center
				= link_to nuclides_path do
					.card-image= image_tag 'nuclides.png', alt: ''
					.card-section= t('title', scope: 'topbar.nuclides', default: "Manage nuclides")
	- if can? :update, Unit
		.cell
			.card.text-center
				= link_to units_path do
					.card-image= image_tag 'units.png', alt: ''
					.card-section= t('title', scope: 'topbar.units', default: "Manage units")
	- if can? :update, MatrixType
		.cell
			.card.text-center
				= link_to matrix_types_path do
					.card-image= image_tag 'matrices.png', alt: ''
					.card-section= t('title', scope: 'topbar.matrix_types', default: "Manage matrix types")
	- if can? :read, Log
		.cell
			.card.text-center
				= link_to logs_path do
					.card-image= image_tag 'logs.png', alt: ''
					.card-section= t('title', scope: 'topbar.logs', default: 'Logs Manage')

app/views/home/historicizes.js.erb
$('table#logs-table').DataTable().ajax.reload();

app/views/home/index.html.haml
%table#jobs-table.display.responsive{ data: { url: home_url(format: :json) } }
  %thead
    %tr
      %th.text-center= t('code', scope: 'jobs.fields', default: 'Code')
      %th.text-left= t('title', scope: 'jobs.fields', default: 'Title')
      %th.text-center= t('customer', scope: 'jobs.fields', default: 'Customer')
      %th.text-center= t('job_manager_ids', scope: 'jobs.fields', default: 'Managers')
      %th.text-center= t('open_at', scope: 'jobs.fields', default: 'Open at')
      %th.text-center= t('planned_closure_at', scope: 'jobs.fields', default: 'Planned closure at')
      %th.text-center= t('close_at', scope: 'jobs.fields', default: 'Close at')
      %th.small-1.text-right{ data: { orderable: "false", searchable: "false"} }
  %tbody

app/views/home/logs.html.haml
#logs.container
  .grid-x
    .small-12.large-2.cell= link_to 'Storicizza logs', historicizes_path, class: 'button radius small expanded', data: { confirm: 'I dati saranno salvati in un file di log sul filesystem del server e la tabella sarà svuotata. Confermi la storicizzazione?' }, remote: true
    .small-12.large-3.cell.end
      %small.text-alert Prossima storicizzazione automatica sarà il 01/01/#{Date.today.year+1}
  %table#logs-table{ data: { url: logs_url(format: :json), button: 'true' } }
    %thead
      %tr
        %th.small-2.text-center= t( 'created_at', scope: 'histories.fields', default: 'Created at' )
        %th.small-1.text-center= t( 'job_title', default: 'Job' )
        %th.small-1.text-center= t( 'action', scope: 'histories.fields', default: 'Action' )
        %th.text-left{ data: { orderable: "false" } }= t( 'body', scope: 'histories.fields', default: 'Description' )
        %th.small-1.text-center= t( 'author', scope: 'histories.fields', default: 'Author' )
    %body
= render 'left_bar' unless @modal == '1' || @nobar == true