config/routes.rb
Rails.application.routes.draw do
  
  # scope "(:locale)", :locale => /#{I18n.available_locales.join('|')}/ do
    localized do
      devise_for :users, :path => "auth", path_names: { sign_in: 'login', sign_out: 'logout' }, controllers: { cas_sessions: 'my_cas' }

      get '/home', to: 'home#index', as: 'home'

      get 'help', to: 'pages#help', defaults: { format: :html }, constraints: { format: :html }
      get 'manual', to: 'pages#manual', defaults: { format: :html }
      get 'changelog', to: 'pages#changelog', defaults: { format: :html }, constraints: { format: :html }
      get 'news', to: 'home#news', defaults: { format: :json }, constraints: { format: :json }, as: :news

      concern :attachable do
        patch :attachment_create, on: :member
        patch :attachment_update
        delete 'attachments/:file_id/delete', on: :member, action: :attachment_destroy, as: :attachment_destroy #, on: :member #, defaults: { format: :js }, constraints: { format: :js }
        get 'attachments/:file_id/download', on: :member, action: :attachment_download, as: :attachment_download
        get :attachments, on: :member
      end

      scope path: '/admin' do
        get :index, to: 'home#admin', as: :admin, defaults: { format: :html }, constraints: { format: :html }
        get :logs, to: 'home#logs'
        get :historicizes, to: 'home#historicizes', defaults: { format: :js }, constraints: { format: :js }
        resources :matrix_types, except: [ :show ] do 
          get 'category', on: :collection, to: 'matrix_types#new', new_category: true, as: 'new_category'
        end
        resources :units, except: [ :show ]
        resources :analisy_types, except: [ :show ]
        resources :nuclides, except: [ :show ]
        resources :instructions, except: [ :show ] do
          get :download, on: :member
        end
        resources :users do
          put 'lock', on: :member, to: 'users#lock'
          put 'unlock', on: :member, to: 'users#unlock'
        end
      end

      resources :jobs, concerns: [ :attachable ] do
        get 'show(/:section)', on: :member, to: 'jobs#show', as: :section, section: /details|contacts|design|roles|attachments/
        get 'print', on: :member, to: 'jobs#print'
        get 'analisies', on: :member, to: 'jobs#analisies'
        get 'printed', on: :member, to: 'jobs#printed', defaults: { format: :pdf }, constraints: { format: :pdf }
        get 'search', on: :collection, defaults: { format: :html }, constraints: { format: :html }
        get 'logs', on: :member, to: 'jobs#logs'
        get 'reopen', on: :member, to: 'jobs#reopen', defaults: { format: :html }, constraints: { format: :html }
        post 'reopened', on: :member, to: 'jobs#reopen', defaults: { format: :js }, constraints: { format: :js }
        get 'deleted', on: :collection, to: 'jobs#deleted', defaults: { format: :html }, constraints: { format: :html }
        get 'edit(/:section)', on: :member, to: 'jobs#edit', as: :section_edit, section: /details|contacts|design|roles|attachments/, defaults: { format: :html }
        resources :import, only: :index do
          get :template, on: :collection, to: 'import#template', defaults: { format: :xlsx }, constraints: { format: :xlsx }
          post :verify, on: :collection, to: 'import#verify' #, defaults: { format: :js }, constraints: { format: :js }
          put :create, on: :collection, to: 'import#create', defaults: { format: :js }, constraints: { format: :js }
        end
        resources :timetables do
          get '(/:section)', on: :collection, to: 'timetables#index', section: /table/, as: :section #, defaults: { format: :html }
          get 'template', on: :collection, to: 'timetables#template', template: /standard|radon/, defaults: { format: :html }, constraints: { format: :html }
          get 'print', on: :collection, to: 'timetables#print', defaults: { format: :xlsx }, constraints: { format: :xlsx }
          put 'changeorder', on: :member, to: 'timetables#changeorder', defaults: { format: :js }, constraints: { format: :js }
        end
        resources :samples do
          resources :analisies do
            resources :results, only: :none do
              match 'results', via: [:get, :patch], on: :collection, to: 'analisies#results', defaults: { format: :html }, constraints: { format: :html }
              get 'edit', on: :member, to: 'analisies#result_edit', defaults: { format: :html }, constraints: { format: :html }, as: :edit
            end
          end
        end
        resources :analisies, only: [:index]
        resources :reports, only: [:index, :create, :delete, :destroy] do
          get '(/:section)(/:report_type)', on: :collection, to: 'reports#index', section: /issued|notissued|cancelled/, report_type: /single|multiple/, as: :filtered
          get :download, on: :member, to: 'reports#download', as: :download, defaults: { format: :pdf }, constraints: { format: :pdf }
          get :delete, on: :member, to: 'reports#delete', as: :delete

        end
      end
      get 'notauthorized', :to => redirect('/401.html')
    end

    root 'home#index'
  #end

  # get '/:locale', to: 'home#index'
end

app/models/analisy.rb
class Analisy < ApplicationRecord
  belongs_to :sample, :class_name => "Sample", :foreign_key => "sample_id"
  belongs_to :type, :class_name => "AnalisyType", :foreign_key => "analisy_type_id"
  has_one    :job, :through => :sample, source: :job
  has_one    :report, -> { issued }, :class_name => 'Report', dependent: :destroy
  has_many   :results, :class_name => "AnalisyResult", :foreign_key => "analisy_id"
  has_many   :nuclides, :through => :results, source: :nuclide
 
  has_many :reports, through: :results, source: :reports
  
  has_many :roles, -> { order role: :asc }, :class_name => "AnalisyUser", :foreign_key => "analisy_id"
  has_many :analisy_technics, -> { where role: 'technic' }, :class_name => "AnalisyUser", :foreign_key => "analisy_id", before_add: [Proc.new {|p,d| d.role = 2} ]
  has_many :analisy_headtests, -> { where role: 'headtest' }, :class_name => "AnalisyUser", :foreign_key => "analisy_id", before_add: [Proc.new {|p,d| d.role = 1} ]
  has_many :analisy_chiefs, -> { where role: 'chief' }, :class_name => "AnalisyUser", :foreign_key => "analisy_id", before_add: [Proc.new {|p,d| d.role = 0} ]
  has_many :analisy_chief_users, :through => :analisy_chiefs, source: :user
  has_many :analisy_headtest_users, :through => :analisy_headtests, source: :user
  has_many :analisy_technic_users, :through => :analisy_technics, source: :user

  accepts_nested_attributes_for :sample, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :analisy_chief_users, reject_if: lambda { |user| user[:_destroy].blank? && user[:id].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :analisy_headtest_users, reject_if: lambda { |user| user[:_destroy].blank? && user[:id].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :analisy_technic_users, reject_if: lambda { |user| user[:_destroy].blank? && user[:id].blank? }, :allow_destroy => true
  
  accepts_nested_attributes_for :results, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reports, reject_if: :all_blank, allow_destroy: true

  has_many :logs, as: :loggable
  accepts_nested_attributes_for :logs, :reject_if => :all_blank, :allow_destroy => true

  attr_accessor :author, :skip_validate, :sample_attributes

  before_validation :prerequisite

  validates :analisy_type_id, presence: true, uniqueness: { :scope => :sample_id }
  validates :reference_at, presence: true, date: true
  
  validates :analisy_chief_user_ids, presence: true, :unless => Proc.new { |analisy| analisy.skip_validate == 'true' }
  validates :analisy_headtest_user_ids, presence: true, :unless => Proc.new { |analisy| analisy.skip_validate == 'true' }
  validates :analisy_technic_user_ids, presence: true, :unless => Proc.new { |analisy| analisy.skip_validate == 'true' }

  before_save :create_log

  default_scope { order(sample_id: :asc, code: :asc) }


  scope :created_in, ->(year) { where( "extract(YEAR from created_at ) = ?", year ) }

  def reference_on
    I18n.l reference_at.to_date if reference_at.present?
  end

  def created_on
    I18n.l created_at.to_date if created_at.present?
  end

  def fullcode
    return "#{ created_at.strftime('%Y') }-#{ code }"
  end

  private

  def prerequisite
    self.author = 'System' if author.blank? || author.nil?
    self.reference_at = Time.now if reference_at.blank?
    analisy_headtests_exists?
    analisy_technics_exists?
  end

  def analisy_headtests_exists?
    if analisy_headtest_user_ids.present?
      analisy_headtest_user_ids.each do | user_id |
        self.analisy_headtest_user_ids.delete(user_id) unless User.headtests.pluck(:id).include?( user_id )
      end
    end
    return analisy_headtest_user_ids.present?
  end
  def analisy_technics_exists?
    if analisy_technic_user_ids.present?
      analisy_technic_user_ids.each do | user_id |
        self.analisy_technic_user_ids.delete(user_id) unless User.technics.pluck(:id).include?( user_id )
      end
    end
    return analisy_technic_user_ids.present?
  end
end

app/controllers/analisies_controller.rb
class AnalisiesController < ApplicationController
  load_and_authorize_resource
  #load_resource :analisy_reports
  before_action :set_user
  before_action :set_job
  before_action :set_sample, except: [:import, :imported, :download_template ]
  before_action :set_analisies, except: [:import, :imported, :download_template ]
  before_action :set_analisy, only: [:show, :edit, :update, :destroy, :results, :report, :delete_report]
  respond_to :html, only: [:index, :new, :edit, :report]
  respond_to :js, only: [:new, :edit, :create, :update, :destroy]
  respond_to :json, only: [:update]
  respond_to :pdf, only: [:report]

  before_action do
    add_breadcrumb "<i class='fa fa-table'> #{I18n.t("breadcrumbs.jobs.all")}</i>".html_safe, :jobs_path, :title => I18n.t("breadcrumbs.jobs.return")
    add_breadcrumb "<i class='fa fa-edit text-trim'> #{@job.title}</i>".html_safe, edit_job_path(id: @job.id), :title => I18n.t("breadcrumbs.jobs.edit")
    add_breadcrumb "<i class='fa fa-edit'>Campione #{@sample.code}</i>".html_safe, edit_job_sample_path(job_id:@job.id, id: @job.id), :title => I18n.t("breadcrumbs.samples.edit")
    add_breadcrumb "<i class='fa fa-table'> #{I18n.t("breadcrumbs.analisies.all")}</i>".html_safe, :job_sample_analisies_path, :title => I18n.t("breadcrumbs.analisies.return")
  end

  # GET /analisies
  # GET /analisies.json
  def index
    @section = 'analisies'
    @modal = params[:modal]
    respond_to do |format|
      format.html do
        if params[:modal] == "1"
          @analisies = @analisies.page( params[:page] ).per(5)
          @icon = ("<i class='fa fa-eyw'></i> ")
          @title = "#{t('show', scope: '', default: 'Show')}"
          render layout: 'modal'
        else
          @analisies = @analisies.page params[:page]
        end
      end
      format.js
      format.json do
        @analisies = @analisies.joins(:sample).joins(:type)
        dt_filter( @analisies )
      end
    end
  end

  # GET /analisies/1
  # GET /analisies/1.json
  def show
    @modal = params[:modal]
    respond_to do |format|
      format.html do
        if params[:modal] == "1"
          @modal = params[:modal]
          @icon = ("<i class='fa fa-eyw'></i> ")
          @title = "#{t('title', scope: 'analisies.show', default: 'Show')}"
          render layout: 'modal'
        end
        add_breadcrumb "<i class='fa fa-wpform'> #{I18n.t("breadcrumbs.analisies.show")}</i>".html_safe
      end
      format.js
    end
  end

  # GET /analisies/new
  def new
    @analisy = @analisies.new
    @analisy.analisy_chiefs.build
    @analisy.analisy_headtests.build
    @analisy.analisy_technics.build
    @analisy.results.build
    @units = Unit.select(:id, :title)
    respond_to do |format|
      format.html do
        if params[:modal] == "1"
          @modal = params[:modal]
          @icon = ("<i class='fa fa-plus'></i><i class='fa fa-flask'></i> ")
          @title = "#{t('title', scope: 'analisies.new', default: 'New analisy')}"
          render layout: 'modal'
        end
        add_breadcrumb "<i class='fa fa-plus'> #{I18n.t("breadcrumbs.analisies.new")}</i>".html_safe
      end
      format.js
    end
  end

  # GET /analisies/1/edit
  def edit
    @analisy.analisy_chiefs.build if @analisy.analisy_chiefs.blank?
    @analisy.analisy_headtests.build if @analisy.analisy_headtests.blank?
    @analisy.analisy_technics.build if @analisy.analisy_technics.blank?
    @analisy_types = @sample.analisies.map{ |a| [ a.type.title, a.type.id ] }
    @units = Unit.select(:id, :title)
    if params[:modal] == "1"
      @modal = params[:modal]
      @icon = ("<i class='fa fa-edit'></i><i class='fa fa-flask'></i> ")
      @title = "#{t('title', scope: 'analisies.edit', default: 'Edit analisy')} #{@analisy.code}"
      render layout: 'modal'
    end
    add_breadcrumb "<i class='fa fa-edit'>Analisi #{@analisy.code}</i>".html_safe
  end

  # POST /analisies
  # POST /analisies.json
  def create
    @analisy = @analisies.new(analisy_params)
    @analisy.author = current_user.label
    respond_to do |format|
      if @analisy.save
        @samples = @job.samples
        @units = Unit.select(:id, :title)
        format.html { redirect_to @analisy, notice: I18n.t('notice', scope: 'analisies.create', default: 'Analisy was successfully created.') }
        format.js
        format.json { render :show, status: :created, location: @analisy }
      else
        @units = Unit.select(:id, :title)
        format.html { render :new }
        format.js { render :new }
        format.json { render json: @analisy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /analisies/1
  # PATCH/PUT /analisies/1.json
  def update
    @analisy.author = current_user.label
    skip = params[:skip_validate]
    @analisy.skip_validate = skip unless skip.blank?
    @modal = params[:modal]
    @analisy_types = @sample.analisies.map{ |a| [ a.type.title, a.type.id ] }
    respond_to do |format|
      if @analisy.update(analisy_params)
        @samples = @job.samples
        @units = Unit.select(:id, :title)
        format.html { redirect_to job_sample_analisy_path(job_id: @analisy.job.id, sample_id: @analisy.sample.id, id: @analisy.id), notice: I18n.t('notice', scope: 'analisies.update', default: 'Analisy was successfully updated.') }
        format.js
        format.json { render :show, status: :ok, location: job_sample_analisy_path(job_id: @analisy.job.id, sample_id: @analisy.sample.id, id: @analisy.id) }
      else
        puts @analisy.errors.full_messages.join(', ')
        @analisy.analisy_chiefs.build if @analisy.analisy_chiefs.blank?
        @analisy.analisy_headtests.build if @analisy.analisy_headtests.blank?
        @analisy.analisy_technics.build if @analisy.analisy_technics.blank?
        @analisy_types = @sample.analisies.map{ |a| [ a.type.title, a.type.id ] }
        @units = Unit.select(:id, :title)
        format.html { render :edit }
        format.js
        format.json { render json: @analisy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /analisies/1
  # DELETE /analisies/1.json
  def destroy
    @analisy.author = current_user.label
    if @analisy.destroy
      @samples = @job.samples
      @analisies = @job.analisies
      respond_to do |format|
        format.html { redirect_to job_samples_path(job_id: @job.id, section: 'analisies') , notice: I18n.t('notice', scope: 'analisies.destroy', default: 'Analisy was successfully destroyed.') }
        format.js
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html
        format.js
        format.json { head :no_content }
      end
    end
  end

  def results
    respond_to do |format|
      format.html do
        @analisy.results.build if @analisy.results.blank?
        add_breadcrumb "<i class='fa fa-list'> #{I18n.t("breadcrumbs.analisies.results")}</i>".html_safe
      end
      format.js do
        @analisy.update(analisy_params) unless params[:analisy].blank?
      end
    end
  end

  private
    def set_user
      @user = current_user
    end

    def set_job
      @job = Job.find(params[:job_id])
    end

    def set_sample
      @sample = @job.samples.find(params[:sample_id])
    end

    def set_analisies
      @analisies = @sample.analisies
    end

    def set_analisy
      @analisy = @analisies.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def analisy_params
      params.require(:analisy).permit(:id, :code, :analisy_type_id, :date_at, :reference_at, :method, :results, :body, :skip_validate, :analisy_chief_user_ids, :analisy_headtest_user_ids, analisy_chiefs_attributes: [ :id, :analisy_id, :user_id, :role ], analisy_headtests_attributes: [ :id, :analisy_id, :role, :user_id ], analisy_technics_attributes: [ :id, :analisy_id, :role, :user_id ], analisy_technic_user_ids: [], results_attributes: [ :id, :nuclide_id, :result, :result_unit_id, :symbol, :indecision, :indecision_unit_id, :absence_analysis, :mcr, :active, :_destroy ], attachments_attributes: [ :title, :body, :category, :file ])
    end

end

app/views/analisies/_analisy.html.haml
%tr{ id: analisy.grid-x }
  %td= analisy.type.title
  %td= analisy.method
  %td.text-center= analisy.date_on
  %td
    %ul= analisy.results.map{ |r| "<li>#{r.full_result_with_nuclide}</li>" }.join('').html_safe
  %td.text-right.button-group
    - if can? :update, analisy
      = link_to fa_icon('edit'), edit_job_sample_analisy_path(job_id: analisy.job.id, sample_id: analisy.sample.id, id: analisy.id, method: @method), class: 'button transparent'
    - if can? :print, analisy
      - if analisy.report.blank?
        = link_to fa_icon('print'), preview_job_sample_analisy_path(job_id: analisy.job.id, sample_id: analisy.sample.id, id: analisy.id, method: @method), class: 'button transparent'
      - else
        = link_to fa_icon('print'), report_job_sample_analisy_path(job_id: analisy.job.id, sample_id: analisy.sample.id, id: analisy.id, method: @method, format: :pdf), class: 'button transparent'
    - if can? :delete, analisy
      = link_to fa_icon('trash'), job_sample_analisy_path(job_id: analisy.job.id, sample_id: analisy.sample.id, id: analisy.id, method: @method), method: :delete, class: 'button transparent', data: { confirm: t('delete', scope: 'confirmations', default: 'The deleted data can not be recovered. If you confirm, all data, connected to it, will be deleted. Are you sure?' ) }

app/views/analisies/_analisy_result_form.html.haml
%tr.valign-middle{ id: f.object.row }
  %td= f.object.nuclide.title
  %td= f.text_field :result, label: 'false', options: { class: "result" }, required: true
  %td= f.select_field :result_unit_id, @units.map{ |u| [ u.title, u.id ] }, { include_blank: false, label: 'false' }, { class: 'input-group-field result_unit' }
  %td= f.select_field :symbol, f.object.symbols, { include_blank: false, label: 'false' }, { class: 'input-group-field symbol' }
  %td= f.text_field :indecision, label: 'false', options: { class: "result" }, required: f.object.symbol != '<', class: 'required'
  %td= f.select_field :indecision_unit_id, @units.map{ |u| [ u.title, u.id ] }, { include_blank: false, label: 'false' }, { class: 'input-group-field indecision_unit' }
  %td= f.text_field :mcr, label: 'false'
  %td= f.text_field :absence_analysis, label: 'false'

app/views/analisies/_delete_report.html.haml
#report
  = form_with( model: @analisy.report, url: report_destroy_job_sample_analisy_path( job_id: @analisy.job.id, sample_id: @analisy.sample.id, id: @analisy.id ), :builder => ExtraFormWith ) do |f|
    .container
      .grid-y
        .cell.callout.alert Stai per annullare questo rapporto di analisi emesso il #{ @analisy.report.issued_on }.<br>Inserisci una motivazione valida che resterà legata al documento annullato.
        .cell= f.textarea :cancellation_reason
        .cell= f.submit_button

app/views/analisies/_new.html.haml
#job= render 'jobs/job_mini'
#sample= render 'samples/sample'
#analisy
	#form= render 'form', analisy: @analisy, render_button: :nil

app/views/analisies/_report.html.haml
%fieldset.container.small-12.large-10
  .grid-x.small-12.cell
    .small-4.large-6.cell
      %legend.text-upcase= t('title', scope: 'reports', default: 'Analisy report - preview')
    - if @analisy.report.blank?
      .small-4.large-3.cell= link_to fa_icon('edit', text: 'Modifica analisi'), edit_job_sample_analisy_path(job_id: @analisy.job.id, sample_id: @analisy.sample.id, id: @analisy.id, method: @method), class: 'button small expanded' if can? :update, @analisy
      .small-4.large-3.cell= link_to fa_icon('print', text: 'Emetti rapporto di analisi'), report_job_sample_analisy_path(job_id: @analisy.job.id, sample_id: @analisy.sample.id, id: @analisy.id, method: @method), class: 'button alert small expanded', data: { confirm: t('create_report', scope: 'confirmations', default: 'Are you sure?'), turbolink: 'false' } if can? :print, @analisy
    - else
      .small-4.large-3.cell= link_to fa_icon('download', text: 'Scarica rapporto di analisi'), download_job_sample_analisy_path(job_id: @analisy.job.id, sample_id: @analisy.sample.id, id: @analisy.id, method: @method), class: 'button small expanded', target: '_blank' if can? :download, @analisy
      .small-4.large-3.cell= link_to fa_icon('trash', text: 'Annulla rapporto di analisi'), report_destroy_job_sample_analisy_path(job_id: @analisy.job.id, sample_id: @analisy.sample.id, id: @analisy.id, method: @method), class: 'button alert small expanded reveal-modal-mini', data: { url: report_destroy_job_sample_analisy_path( job_id: @analisy.job.id, sample_id: @analisy.sample.id, id: @analisy.id, modal: 1 ) } if can? :deletereport, @analisy
  .grid-x.small-12.cell
    .small-12.large-4.cell
      %label.text-bold.text-upcase= t('code', scope: 'analisyreports.fields', default: 'Id report of analisy')
    .small-12.large-2.cell.text-box= @analisy.code
    .small-12.large-1.cell.text-right
      %label.text-bold.text-upcase= t('revision', scope: 'analisyreports.fields', default: 'Revision')
    .small-12.large-1.cell.end.text-box= @analisy.revision
  .grid-x.small-12.cell
    .small-12.large-4.cell
      %label.text-bold.text-upcase= t('issued_at', scope: 'analisyreports.fields', default: 'Issued at')
    .small-12.large-8.cell.text-box= @analisy.report.blank? ? t('not_issued', scope: 'analisyreports.fields', default: 'Not issued').upcase : @analisy.report.issued_on
  .grid-x.small-12.cell
    .small-12.large-4.cell
      %label.text-bold.text-upcase= t('job', scope: 'analisyreports.fields', default: 'Job')
    .small-12.large-8.cell.text-box= @analisy.job.code
  .grid-x.small-12.cell
    .small-12.large-4.cell
      %label.text-bold.text-upcase= t('customer', scope: 'analisyreports.fields', default: 'Customer')
    .small-12.large-8.cell.text-box= @analisy.job.customer
  .grid-x.small-12.cell
    .small-12.large-4.cell
      %label.text-bold.text-upcase= t('object', scope: 'analisyreports.fields', default: 'Job object')
    .small-12.large-8.cell.text-area= @analisy.job.title
  .grid-x.small-12.cell
    .small-12.large-4.cell
      %label.text-bold.text-upcase= t('device', scope: 'analisyreports.fields', default: 'Device')
    .small-12.large-8.cell.text-box= @analisy.sample.device
  .grid-x.small-12.cell
    .small-12.large-4.cell
      %label.text-bold.text-upcase= t('start_at', scope: 'analisyreports.fields', default: 'Start at')
    .small-12.large-8.cell.text-box= @analisy.sample.start_on
  .grid-x.small-12.cell
    .small-12.large-4.cell
      %label.text-bold.text-upcase= t('stop_at', scope: 'analisyreports.fields', default: 'Stop at')
    .small-12.large-8.cell.text-box= @analisy.sample.stop_on
  .grid-x.small-12.cell
    .small-12.large-4.cell
      %label.text-bold.text-upcase= t('reference_at', scope: 'analisyreports.fields', default: 'Reference at')
    .small-12.large-8.cell.text-box= @analisy.reference_on.blank? ? t('not_inserted', scope: 'analisyreports.fields', default: 'Not inserted').upcase : @analisy.reference_on
  .grid-x.small-12.cell
    .small-12.large-4.cell
      %label.text-bold.text-upcase= t('sample', scope: 'analisyreports.fields', default: 'Sample')
    .small-12.large-8.cell.text-box= @analisy.sample.code
  .grid-x.small-12.cell
    .small-12.large-4.cell
      %label.text-bold.text-upcase= t('analisytype', scope: 'analisyreports.fields', default: 'Analisy type')
    .small-12.large-8.cell.text-box= @analisy.type.title
  .grid-x.small-12.cell
    .small-12.large-4.cell
      %label.text-bold.text-upcase= t('results', scope: 'analisyreports.fields', default: 'Results')
  .grid-x.small-12.cell
    .text-area-big
      %ul.nop
        - @analisy.results.each do | result |
          %li= result.full_result_with_nuclide
  .grid-x.small-12.cell
    .text-area-big
      %ul.nop
        - @analisy.results.each do | result |
          %li= result.body
  .grid-x.small-12.cell
    .text-area-big
  .grid-x.small-12.cell
    .small-12.large-4.cell
      %label.text-bold.text-upcase= t('body', scope: 'analisyreports.fields', default: 'Note')
    .small-12.large-8.cell.text-area= @analisy.body
  .grid-x.small-12.cell
    .small-12.large-4.cell
      %label.text-bold.text-upcase= t('attachments', scope: 'analisyreports.fields', default: 'Attachments')
    .small-12.large-8.cell.text-area
      %ul.nop
        - @analisy.job.attachments.each do | attach |
          %li= attach.file_file_name
  .grid-x.small-12.cell
    .small-12.large-4.cell
      %label.text-bold.text-upcase= t('technician', scope: 'analisyreports.fields', default: "Laboratory technician")
    .small-12.large-8.cell.text-box= @analisy.analisy_technic_users.blank? ? t('not_found', scope: 'analisyreports.fields', default: 'Not found').upcase : @analisy.analisy_technic_users.pluck(:label).join(', ')
  .grid-x.small-12.cell
    .small-12.large-4.cell
      %label.text-bold.text-upcase= t('responsible_for_testing', scope: 'analisyreports.fields', default: "responsible for testing")
    .small-12.large-8.cell.text-box= @analisy.analisy_headtest_users.blank? ? t('not_found', scope: 'analisyreports.fields', default: 'Not found').upcase : @analisy.analisy_headtest_users.pluck(:label).join(', ')
  .grid-x.small-12.cell
    .small-12.large-4.cell
      %label.text-bold.text-upcase= t('chief', scope: 'analisyreports.fields', default: "Manager")
    .small-12.large-8.cell.text-box= @analisy.analisy_chief_users.blank? ? t('not_found', scope: 'analisyreports.fields', default: 'Not found').upcase : @analisy.analisy_chief_users.pluck(:label).join(', ')

app/views/analisies/delete_report.html.haml
= render 'delete_report'

app/views/analisies/delete_report.js.erb
$('#modal-body').html("<%= escape_javascript( render 'delete_report' ) %>");

app/views/analisies/edit.html.haml
#analisy= render 'edit'
- unless @modal == '1'
  - content_for :left do
    = render 'left_bar'

app/views/analisies/index.html.haml
= render 'summary', job: @job, sample: @sample, analisy: ''
= render 'analisies'
- unless @modal == '1'
	- content_for :left do
		= render 'left_bar'

app/views/analisies/new.html.haml
#analisy= render 'new'